version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
  redis:
    image: redis:latest
    container_name: redis
  backend:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    container_name: backend
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    container_name: nginx
    ports:
      - '4000:80'
  frontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    container_name: frontend
    volumes:
      - /app/node_modules
      - ./client:/app
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    container_name: worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      